### ISSUE TITLE
Hang in batch `Command`

### ISSUE THREAD

**Issue by finestructure** [vapor/async-kit#104]
This is a follow-up of a [Discord discussion](https://discord.com/channels/431917998102675485/519613337638797315/1097832913694883840), FYI @0xTim !

----

We're seeing the following error in one of our Vapor batch jobs every once in a while (a few times per month, maybe once a week - hard to quantify precisely):

```
│   [ ERROR ] Connection request timed out. This might indicate a connection deadlock in your application. If you're running long running requests, consider increasing your connection timeout. [component: server, database-id: psql]                │
```

When this message occurs, the job HANGS - i.e. it locks up and does not terminate, preventing all further processing.

In normal operation the job spins up and typically processes for 3-6 seconds, running a number of queries against the Github APIs (we're processing batches of 25 Swift packages, updating Github metadata in the Swift Package Index).

I've done a little research and there seem to be a couple of cases where this can happen:

1) too many db connections
2) an [error handling problem in networking code](https://discord.com/channels/431917998102675485/519613337638797315/1071481521627742280)

I suspect it's 2). Last I checked we're not exhausing our db connections and our db utilization across our two envs is <15% and <10%.

I believe this issue first started happening after moving to async/await. This may be due to how we're launching async processes from a `Command` via our own [`AsyncCommand`](https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/blob/main/Sources/App/Commands/AsyncCommand.swift). (We previously used a semaphore-based implementation which also encountered hangs.)

Our logs show no unusual activity around the error, although we've not yet had it happen with `DEBUG` logging enabled.

----

We're also tracking this issue here: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2227, and I'll be adding more observations as they happen there.

**Comment by 0xTim** [comment]
@finestructure Is this still an issue? Have you tried with the latest async kit? That had a load of improvements to connection pooling to stop these kind of issues

**Comment by finestructure** [comment]
Unfortunately, it is. We're on async-kit 1.18.0 and our analysis job on dev is hanging right now. I've started tracking just our prod occurrences of it here: https://github.com/SwiftPackageIndex/SwiftPackageIndex-Server/issues/2227#issuecomment-1675743222.

I'm unsure what else I could do to track this down - and it's infrequent enough that it's just easier to respond and restart the job when it happens that dig into this further. Let me know if there's anything I can do to gather more info!

**Comment by gwynne** [comment]
My current best guess is that this is happening because the `queues` package doesn't actually interact with the `fluent` provider package- the result being that when you use `context.application.db()` with a `QueueContext`, you end up with a database that's sourced from the connection pool of whatever event loop the application happens to come up with at that moment, rather than the one the queue is actually running on.

@finestructure To test this theory,

1. Add this extension to FluentKit.Databases:
```swift
extension FluentKit.Databases {
    public func db(_ id: DatabaseID?, on eventLoop: any EventLoop) -> any Database {
        self.databases
            .database(
                id,
                logger: self.logger,
                on: eventLoop,
                history: self.fluent.history.historyEnabled ? self.fluent.history.history : nil,
                pageSizeLimit: self.fluent.pagination.pageSizeLimit
            )!
    }
}
```
2. In your `Job` (or `AsyncJob`), use `context.application.db(.psql, on: context.eventLoop)` anywhere you'd otherwise use `context.application.db()`.

If that fixes it, I will look into adding appropriate support to the packages in question.

**Comment by finestructure** [comment]
Thanks for taking a look, @gwynne ! We're not using the `queues` package. This is a "vapor command" that we're running on a schedule (every ~20s). It's runtime is a few seconds.

```yml
  analyze:
    image: registry.gitlab.com/finestructure/swiftpackageindex:${VERSION}
    <<: *shared
    depends_on:
      - migrate
    entrypoint: ["/bin/bash"]
    command: ["-c", "--",
      "trap : TERM INT; while true; do ./Run analyze --env ${ENV} --limit ${ANALYZE_LIMIT:-25}; sleep ${ANALYZE_SLEEP:-20}; done"
    ]
    deploy:
      resources:
        limits:
          memory: 4GB
      restart_policy:
        max_attempts: 5
    networks:
      - backend
```

Would your theory still apply?

**Comment by gwynne** [comment]
@finestructure Even more so, actually, since by default a `Command` doesn't run on _any_ event loop (and an `AsyncCommand` will be running on a Concurrency task). In either case, you can still use the `extension` I suggested, but at the entry point to your command, do:
```swift
let eventLoop = context.application.eventLoopGroup.any())
let db = context.application.db(.psql, on: eventLoop)
```
Then make sure to use `db` everywhere (and use `eventLoop` in any place you might need to refer to an event loop, if any). The goal is the same: Make sure you do everything that's related to an event loop (versus a Concurrency task context etc.) on the _same_ event loop.

**Comment by gwynne** [comment]
This has been resolved by other work.
