### ISSUE TITLE
Ability to set minConnections for pool

### ISSUE THREAD

**Issue by MihaelIsaev** [vapor/async-kit#24]
It would be great to have an ability to configure minimum size of the connection pool

**Comment by tanner0101** [comment]
Moving this to NIOKit since that is where `ConnectionPool` lives now.

**Comment by MrLotU** [comment]
How/when would this be beneficial? It’d still have a max and pick a new connection up when needed? Or would you always have `x` amount of connections connected?

**Comment by MrMage** [comment]
Might slightly decrease latency (especially in case of a sudden "burst" of parallel requests) because we are more likely to not need to fire up a new connection for these. But I agree that the semantics are a bit unclear per se, and it should also have less effect once the connection pool is "warm" (i.e. filled with as many connections are needed for regular operation).

**Comment by MrLotU** [comment]
But while decreasing latency, would this not also increase the performance hit by keeping alive connections that are not needed? (I guess that'd be a tradeoff an end user would have to make)

**Comment by MrMage** [comment]
Yes, but the performance hit of excess idle connections should be negligible.

**Comment by MrLotU** [comment]
I'm not into the whole performance world enough to judge that, so I'll take your word for that.

In this case it seems like a good addition, feel free to open a PR :)
